services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ahXu8eafish1bee2Eedo
      MYSQL_DATABASE: blog
      MYSQLD_PORT: 3306
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mnt/mysql:/var/lib/mysql
      - ./backup_db/backup.sql:/docker-entrypoint-initdb.d/backup.sql

  web:
    build: src
    container_name: web
    depends_on:
      - mysql
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ahXu8eafish1bee2Eedo
      DB_NAME: blog
    ports:
      - "8080:8080"
    volumes:
      - ./mnt/web/configs/:/mnt/web/configs/
      - ./mnt/web/static/:/mnt/web/static/
      - ./mnt/web/static/media:/mnt/web/static/media
      - ./src/ui/:/src/ui/
