env: "local" #prod

jwt_secret: "JWTSecretT0Ken$!#@*(!$)!"

url_1: "https://ip:port" #шифрованные файлы
url_2: "https://ip:port" #дешифратор

server:
  address: "localhost"
  port: "8080"
  timeout: 45s

database:
  db_name: "blog_electronchik"
  hostname: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "9298"