env: "local" #prod
token_ttl: 1h
grpc:
  port: 44044
  timeout: 10h

server:
  address: "localhost"
  port: "8080"
  timeout: 45s

database:
  db_name: "niitzi"
  hostname: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "9298"