env: "local" #prod

jwt_secret: "JWTSecretT0Ken$!#@*(!$)!"

server:
  address: "localhost"
  port: "8080"
  timeout: 45s

database:
  db_name: "blog_electronchik"
  hostname: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "Qweaz123"