version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: myapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9298
      MYSQL_DATABASE: blog_electronchik
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: myapp_go
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 9298
      DB_NAME: blog_electronchik
    ports:
      - "8080:8080"
    volumes:
      - ./mnt:/app/mnt
      - ./configs:/app/configs
      - ./internal:/app/internal
      - ./ui/dist:/app/ui/dist

  nginx:
    image: nginx:stable-alpine
    container_name: myapp_nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./mnt:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
